### ISSUE TITLE
Create basic project infrastructure

### ISSUE THREAD

**Issue by sreznick** [sreznick/jcsv-xxl#1]
Use Gradle as build tool

**Comment by DLochmelis33** [comment]
Наглым образом запушил без PR, но там и пушить почти нечего. Правда же, что этот issue про уровень Hello World?

**Comment by sreznick** [comment]
Нормально для начала.

Было бы здорово сразу добавить какой-никакой юнит-тест прикрутить.

Тогда я бы сразу CI-настроил.

**Comment by sreznick** [comment]
https://docs.gradle.org/current/samples/sample_building_java_applications.html

**Comment by sreznick** [comment]
Done
